config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: main
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/rizac/eGSIM:
      branch: main
      repo: https://github.com/rizac/eGSIM
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/rizac/eGSIM git:
        commands:
        - /usr/bin/env sh .sqa/script.stealthy-cornflower-macaque.sh
        container: qc.acc_squirrely-auburn-dragon
  QC.Doc:
    repos:
      github.com/rizac/eGSIM find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.gummy-heliotrope-owl.sh
        container: qc.doc_cozy-blue-koala
      github.com/rizac/eGSIM git:
        commands:
        - /usr/bin/env sh .sqa/script.snazzy-chartreuse-monster.sh
        container: qc.doc_wheezy-amaranth-tortoise
      github.com/rizac/eGSIM markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.nerdy-wheat-zebra.sh
        container: qc.doc_gummy-heliotrope-dunker
  QC.Lic:
    repos:
      github.com/rizac/eGSIM licensee:
        commands:
        - /usr/bin/env sh .sqa/script.beady-chestnut-angelfish.sh
        container: qc.lic_geeky-grey-quoll
  QC.Sec:
    repos:
      github.com/rizac/eGSIM bandit:
        commands:
        - /usr/bin/env sh .sqa/script.flaky-jade-bison.sh
        container: qc.sec_tacky-cinnamon-maltese
  QC.Sty:
    repos:
      github.com/rizac/eGSIM flake8:
        commands:
        - /usr/bin/env sh .sqa/script.pretty-saffron-markhor.sh
        container: qc.sty_nerdy-viridian-macaque
      github.com/rizac/eGSIM jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.chummy-bronze-mandrill.sh
        container: qc.sty_chummy-orchid-rabbit
  QC.Uni:
    repos:
      github.com/rizac/eGSIM pytest:
        commands:
        - /usr/bin/env sh .sqa/script.pasty-cardinal-donkey.sh
        container: qc.uni_droopy-goldenrod-budgerigar
  QC.Ver:
    repos:
      github.com/rizac/eGSIM get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.homey-denim-tamarin.sh
        container: qc.ver_gimpy-cyan-fly
timeout: 5400
