config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/2.2.1
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/rizac/eGSIM:
      branch: main
      repo: https://github.com/rizac/eGSIM
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/rizac/eGSIM git:
        commands:
        - /usr/bin/env sh .sqa/script.muzzy-ultramarine-mist.sh
        container: qc.acc_cloudy-olivine-wombat
  QC.Doc:
    repos:
      github.com/rizac/eGSIM find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.lanky-violet-heron.sh
        container: qc.doc_wiggy-indigo-cuttlefish
      github.com/rizac/eGSIM git:
        commands:
        - /usr/bin/env sh .sqa/script.sloppy-russet-stoat.sh
        container: qc.doc_hasty-cinnamon-fowl
      github.com/rizac/eGSIM markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.zippy-apricot-antelope.sh
        container: qc.doc_crappy-burgundy-mau
  QC.Lic:
    repos:
      github.com/rizac/eGSIM licensee:
        commands:
        - /usr/bin/env sh .sqa/script.trippy-turquoise-earwig.sh
        container: qc.lic_blurry-khaki-loon
  QC.Sec:
    repos:
      github.com/rizac/eGSIM bandit:
        commands:
        - /usr/bin/env sh .sqa/script.squeaky-charcoal-wasp.sh
        container: qc.sec_shaggy-viridian-booby
  QC.Sty:
    repos:
      github.com/rizac/eGSIM flake8:
        commands:
        - /usr/bin/env sh .sqa/script.messy-taupe-oyster.sh
        container: qc.sty_messy-razzmatazz-newt
      github.com/rizac/eGSIM jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.blurry-cyan-rhinoceros.sh
        container: qc.sty_muggy-gold-wasp
  QC.Uni:
    repos:
      github.com/rizac/eGSIM pytest:
        commands:
        - /usr/bin/env sh .sqa/script.pokey-pumpkin-lemur.sh
        container: qc.uni_snoopy-violet-baboon
  QC.Ver:
    repos:
      github.com/rizac/eGSIM get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.beady-rose-baboon.sh
        container: qc.ver_flimsy-alizarin-barracuda
timeout: 5400
