config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: main
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/rizac/eGSIM:
      branch: main
      repo: https://github.com/rizac/eGSIM
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/rizac/eGSIM git:
        commands:
        - /usr/bin/env sh .sqa/script.grumpy-gamboge-ferret.sh
        container: qc.acc_jumpy-salmon-leopard
  QC.Doc:
    repos:
      github.com/rizac/eGSIM find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.gimpy-razzmatazz-lynx.sh
        container: qc.doc_freaky-linen-barnacle
      github.com/rizac/eGSIM git:
        commands:
        - /usr/bin/env sh .sqa/script.baggy-coral-yak.sh
        container: qc.doc_skimpy-periwinkle-hyrax
      github.com/rizac/eGSIM markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.stinky-fuchsia-kudu.sh
        container: qc.doc_smelly-amber-liger
  QC.Lic:
    repos:
      github.com/rizac/eGSIM licensee:
        commands:
        - /usr/bin/env sh .sqa/script.silly-cinnamon-wallaby.sh
        container: qc.lic_shabby-amaranth-llama
  QC.Sec:
    repos:
      github.com/rizac/eGSIM bandit:
        commands:
        - /usr/bin/env sh .sqa/script.ugly-crimson-emu.sh
        container: qc.sec_shaggy-silver-monkey
  QC.Sty:
    repos:
      github.com/rizac/eGSIM flake8:
        commands:
        - /usr/bin/env sh .sqa/script.flimsy-eggplant-kingfisher.sh
        container: qc.sty_trippy-mustard-grasshopper
      github.com/rizac/eGSIM jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.crappy-mustard-camel.sh
        container: qc.sty_sleepy-orchid-opossum
  QC.Uni:
    repos:
      github.com/rizac/eGSIM pytest:
        commands:
        - /usr/bin/env sh .sqa/script.stinky-linen-mastiff.sh
        container: qc.uni_hilly-platinum-frog
  QC.Ver:
    repos:
      github.com/rizac/eGSIM get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.cheeky-brass-newfoundland.sh
        container: qc.ver_stuffy-saffron-mule
timeout: 5400
